name: hrm_v1
channels: [conda-forge, defaults]
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - ipykernel
  - matplotlib
  - seaborn
  - pip:
      - einops
      - transformers
      - accelerate
      - huggingface_hub
      - wandb
      - omegaconf
      - hydra-core
      - coolname
      - argdantic

# for flash attention: pip install https://huggingface.co/lldacing/flash-attention-windows-wheel/resolve/main/flash_attn-2.7.4%2Bcu124torch2.5.1cxx11abiFALSE-cp310-cp310-win_amd64.whl --force-reinstall --no-dep