name: hrm_v1
channels: [conda-forge, defaults]
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - ipykernel
  - matplotlib
  - seaborn
  - pip:
      - einops
      - transformers
      - accelerate
      - huggingface_hub
      - wandb
      - omegaconf
      - hydra-core
      - coolname
      - argdantic
