defaults:
  - arch: hrm_v1
  - _self_

hydra:
  output_subdir: null

data_path: data/city-logistics-1k

# SIMPLE DEBUGGING SETTINGS
global_batch_size: 16
epochs: 3
eval_interval: 1
checkpoint_every_eval: True

# SIMPLE LEARNING RATE
lr: 1e-3
lr_min_ratio: 0.1
lr_warmup_steps: 50  # Much shorter warmup

# STANDARD HYPERPARAMETERS
beta1: 0.9
beta2: 0.95
weight_decay: 0.01
puzzle_emb_weight_decay: 0.01
puzzle_emb_lr: 1e-3

# DEBUGGING FLAGS
debug_mode: true
verbose_training: true
seed: 42